services:
  dokus:
    image: r.ispa.dev/base/dokus
    #ports: 
    #  - ${DOKUS_EXTERNAL_PORT:-1122}:8080
    environment:
      DOKUS_ROOT_PASSWORD: ${DOKUS_ROOT_PASSWORD:-DoKus}
    restart: unless-stopped
    volumes:
      - dokus:/root/.dokus/root
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${STACKNAME:?err}-dokus.entrypoints=http"
      - "traefik.http.routers.${STACKNAME:?err}-dokus.rule=Host(`${DOKUS_URL:?err}`)"
      - "traefik.http.middlewares.${STACKNAME:?err}-dokus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${STACKNAME:?err}-dokus-ipwhitelist.ipwhitelist.sourcerange=${DOKUS_IP_WHITELIST:-0.0.0.0/0}"
      - "traefik.http.routers.${STACKNAME:?err}-dokus.middlewares=${STACKNAME:?err}-dokus-https-redirect"
      - "traefik.http.routers.${STACKNAME:?err}-dokus-secure.entrypoints=https"
      - "traefik.http.routers.${STACKNAME:?err}-dokus-secure.rule=Host(`${DOKUS_URL:?err}`)"
      - "traefik.http.routers.${STACKNAME:?err}-dokus-secure.middlewares=${STACKNAME:?err}-dokus-ipwhitelist"
      - "traefik.http.routers.${STACKNAME:?err}-dokus-secure.tls=true"
      - "traefik.http.routers.${STACKNAME:?err}-dokus-secure.tls.certresolver=http"
      - "traefik.http.routers.${STACKNAME:?err}-dokus-secure.service=${STACKNAME:?err}-dokus"
      - "traefik.http.services.${STACKNAME:?err}-dokus.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
volumes:
  dokus:

networks:
  proxy:
    external: true
