services:
  stanley:
    image: r.ispa.dev/lotus/stanley:${STANLEY_VERSION:?err}
    restart: unless-stopped
    volumes: 
      - ${STANLEY_VOLUME_CONFIG:?err}:/var/www/shared
      - db:/var/www/current/db

volumes:
  db: